import type { Planet } from "./types";

export const PLANET_IDS = [
  "mercury",
  "venus",
  "earth",
  "mars",
  "jupiter",
  "saturn",
  "uranus",
  "neptune",
] as const;
export type PlanetId = (typeof PLANET_IDS)[number];

export const PLANETS: Planet[] = [
  {
    id: "mercury",
    name: "Mercurio",
    color: "#b9a58d",
    radiusKm: 2439.7,
    distanceFromSunAU: 0.39,
    distanceFromEarthMillionKm: 91.7,
    temperatureC: 167,
    gravityMs2: 3.7,
    moons: 0,
    orbitalPeriodDays: 88,
    rotationPeriodHours: 1407.6,
    axialTiltDegrees: 0.034,
    atmosphere: [
      { gas: "Oxígeno", percentage: 42 },
      { gas: "Sodio", percentage: 29 },
      { gas: "Hidrógeno", percentage: 22 },
    ],
    description: "El planeta más pequeño y rápido del sistema solar.",
  },
  {
    id: "venus",
    name: "Venus",
    color: "#e4ad68",
    radiusKm: 6051.8,
    distanceFromSunAU: 0.72,
    distanceFromEarthMillionKm: 41.4,
    temperatureC: 464,
    gravityMs2: 8.87,
    moons: 0,
    orbitalPeriodDays: 224.7,
    rotationPeriodHours: -5832.5,
    axialTiltDegrees: 177.4,
    atmosphere: [
      { gas: "Dióxido de carbono", percentage: 96.5 },
      { gas: "Nitrógeno", percentage: 3.5 },
    ],
    description:
      "Un mundo cubierto por nubes y con el efecto invernadero más intenso.",
  },
  {
    id: "earth",
    name: "Tierra",
    color: "#4c9be8",
    radiusKm: 6371,
    distanceFromSunAU: 1,
    distanceFromEarthMillionKm: 0,
    temperatureC: 15,
    gravityMs2: 9.81,
    moons: 1,
    orbitalPeriodDays: 365.25,
    rotationPeriodHours: 23.93,
    axialTiltDegrees: 23.4,
    atmosphere: [
      { gas: "Nitrógeno", percentage: 78.08 },
      { gas: "Oxígeno", percentage: 20.95 },
      { gas: "Argón", percentage: 0.93 },
    ],
    description: "El único planeta conocido que alberga vida.",
  },
  {
    id: "mars",
    name: "Marte",
    color: "#c95e45",
    radiusKm: 3389.5,
    distanceFromSunAU: 1.52,
    distanceFromEarthMillionKm: 78.3,
    temperatureC: -63,
    gravityMs2: 3.71,
    moons: 2,
    orbitalPeriodDays: 687,
    rotationPeriodHours: 24.62,
    axialTiltDegrees: 25.2,
    atmosphere: [
      { gas: "Dióxido de carbono", percentage: 95.3 },
      { gas: "Nitrógeno", percentage: 2.7 },
      { gas: "Argón", percentage: 1.6 },
    ],
    description:
      "El planeta rojo, con volcanes gigantes y antiguos cauces de agua.",
  },
  {
    id: "jupiter",
    name: "Júpiter",
    color: "#d9ad7e",
    radiusKm: 69911,
    distanceFromSunAU: 5.2,
    distanceFromEarthMillionKm: 628.7,
    temperatureC: -110,
    gravityMs2: 24.79,
    moons: 95,
    orbitalPeriodDays: 4331,
    rotationPeriodHours: 9.93,
    axialTiltDegrees: 3.1,
    atmosphere: [
      { gas: "Hidrógeno", percentage: 89.8 },
      { gas: "Helio", percentage: 10.2 },
    ],
    description: "El gigante gaseoso, famoso por su Gran Mancha Roja.",
  },
  {
    id: "saturn",
    name: "Saturno",
    color: "#dfc38d",
    radiusKm: 58232,
    distanceFromSunAU: 9.54,
    distanceFromEarthMillionKm: 1275,
    temperatureC: -140,
    gravityMs2: 10.44,
    moons: 146,
    orbitalPeriodDays: 10747,
    rotationPeriodHours: 10.7,
    axialTiltDegrees: 26.7,
    atmosphere: [
      { gas: "Hidrógeno", percentage: 96.3 },
      { gas: "Helio", percentage: 3.25 },
    ],
    description:
      "Un gigante gaseoso rodeado por un espectacular sistema de anillos.",
  },
  {
    id: "uranus",
    name: "Urano",
    color: "#83d4d7",
    radiusKm: 25362,
    distanceFromSunAU: 19.19,
    distanceFromEarthMillionKm: 2724,
    temperatureC: -195,
    gravityMs2: 8.69,
    moons: 28,
    orbitalPeriodDays: 30589,
    rotationPeriodHours: -17.24,
    axialTiltDegrees: 97.8,
    atmosphere: [
      { gas: "Hidrógeno", percentage: 82.5 },
      { gas: "Helio", percentage: 15.2 },
      { gas: "Metano", percentage: 2.3 },
    ],
    description: "Un gigante helado que gira casi tumbado sobre su órbita.",
  },
  {
    id: "neptune",
    name: "Neptuno",
    color: "#4169c1",
    radiusKm: 24622,
    distanceFromSunAU: 30.06,
    distanceFromEarthMillionKm: 4347,
    temperatureC: -200,
    gravityMs2: 11.15,
    moons: 16,
    orbitalPeriodDays: 60190,
    rotationPeriodHours: 16.11,
    axialTiltDegrees: 28.3,
    atmosphere: [
      { gas: "Hidrógeno", percentage: 80 },
      { gas: "Helio", percentage: 19 },
      { gas: "Metano", percentage: 1 },
    ],
    description:
      "El planeta más lejano, con los vientos más veloces conocidos.",
  },
];

export const PLANETS_BY_ID = new Map<PlanetId, Planet>(
  PLANETS.map((planet) => [planet.id as PlanetId, planet]),
);

export const getPlanet = (id: string): Planet | undefined => {
  return PLANETS_BY_ID.get(id as PlanetId);
};
